mybatis:
  type-aliases-package: com.foo.model
  type-handlers-package: com.foo.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useSSL=false&requireSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      max-active: 200
      min-idle: 1
      initialize: false
      max-wait: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 300000